plugins {
    id 'net.minecraftforge.gradle' version '6.0.+'
    id 'com.gradleup.shadow' version '9.2.0+'
    id 'eclipse'
    id 'net.darkhax.curseforgegradle' version '1.3.+'
    id 'com.modrinth.minotaur' version '2.+'
}

group = project.mod_group
version = project.mod_version

base {
    archivesName = "${project.mod_name}-${project.minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(project.java_version.toInteger())
}

sourceSets {
    main {
        java {
            srcDirs(
                "guilib/src/",
                "linkableapi/src/",
                "contentPackLib/src"
            )
        }
    }
}

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'

    accessTransformer = file(
        'src/main/resources/META-INF/accesstransformer.cfg'
    )

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
        }

        server {
            property 'forge.logging.console.level', 'debug'
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

test {
    useJUnitPlatform()
}

jar {
    archiveClassifier.set("old")
}

shadowJar {
    archiveClassifier.set('')
    configurations = []
    relocate 'com.troblecodings.linkableapi', "${project.group}.signals.shadow.linkableapi"
    relocate 'com.troblecodings.guilib', "${project.group}.signals.shadow.guilib"
    relocate 'com.troblecodings.core', "${project.group}.signals.shadow.core"
    relocate 'com.troblecodings.contentpacklib', "${project.group}.signals.shadow.contentpacklib"

    manifest {
        attributes([
            "Specification-Title": project.mod_name,
            "Specification-Vendor": "troblecodings",
            "Specification-Version": project.version,
            "Implementation-Title": project.mod_name,
            "Implementation-Version": project.version,
            "Implementation-Vendor": "troblecodings",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    from("changelog.md")
    from("LICENSE")
}

reobf {
    shadowJar {}
}

def releaseJar = file("$buildDir/libs/${project.mod_name}-${project.minecraft_version}-${project.mod_version}.jar")

tasks.register("publishCurseforge", net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    dependsOn("reobfShadowJar")

    def key = System.getenv("CURSETOKEN")
    if (key == null)
        key = 'dev'
    apiToken = key

    def mainFile = upload(project.curseforge_project_id, releaseJar)
    mainFile.changelog = file("changelog.md").text
    mainFile.changelogType = 'markdown'
    mainFile.releaseType = 'release'
    mainFile.addModLoader("${project.loader}")
    mainFile.addEnvironment("Client", "Server")
    mainFile.addGameVersion("${project.minecraft_version}")
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")

    projectId = project.modrinth_project_id

    versionNumber = project.version
    versionName = "${project.mod_name} ${project.version}"

    uploadFile = releaseJar

    gameVersions = [project.minecraft_version]
    loaders = [project.loader.toLowerCase()]

    changelog = file("changelog.md").text
}

tasks.register("publishModrinth") {
    dependsOn("reobfShadowJar")
    dependsOn("modrinth")
}
