# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Meta
mod_name=OpenSignals
mod_group=com.troblecodings
mod_version=3.8.4

# Minecraft
minecraft_version=1.18.2

# Forge
forge_version=40.1.86
loader=forge

# Java
java_version=17

# Publishing
curseforge_project_id=440990
modrinth_project_id=1FAZm7aq