# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Meta
mod_id=opensignals
mod_name=OpenSignals
mod_group=com.troblecodings
mod_version=3.8.2

# Minecraft
minecraft_version=1.12.2
loader=forge

# Forge
forge_version=14.23.5.2860

# Java
java_version=8

# Publishing
curseforge_project_id=440990
modrinth_project_id=opensignals