modLoader="javafml"
loaderVersion="["${forgeversion}",)"
issueTrackerURL="https://github.com/MrTroble/Open-Signals/issues"
license="Apache License Version 2.0"

[[mods]]
modId="${modid}"
version="${version}"
displayName="${modname}"
displayURL="https://troblecodings.com/"
authors="${author}"
credits="German Immersive Railroading Community"
description="This mod adds a lot of German railway signals. You are able to controlle them via a manuell interface, redstone or our own signal box! You can also add your own signals via a contentpack. Please read the wiki."

[[dependencies.${modid}]]
    modId="forge" 
    mandatory=true 
    versionRange="[${forgeversion},)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcversion}]"
    ordering="NONE"
    side="BOTH"
