package com.troblecodings.signals.enums;

public enum SignalControllerNetwork {

    SEND_MODE, SEND_RS_PROFILE, SEND_PROPERTY, SET_PROFILE, REMOVE_PROPERTY, REMOVE_PROFILE,
    SET_RS_INPUT_PROFILE, REMOVE_RS_INPUT_PROFILE, UNLINK_INPUT_POS;

}