name: Build & Publish Mod

on:
  push:
    branches:
      - "*-master"

  pull_request:
    branches:
      - "*-master"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: temurin
        cache: gradle

    - name: Make Gradle executable
      run: chmod +x ./gradlew
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Build
      run: ./gradlew build

    - name: Publish
      if: github.event_name == 'push' && github.ref_protected && github.ref_type == 'branch'
      run: ./gradlew publishMods
      env:
        CURSETOKEN: ${{ secrets.CURSETOKEN }}
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}